title: Alvaro Robledo
author: Alvaro Robledo Vega
description: > # Meta description of Homepage
  Hey there! Since 2013, Hamsoft Uganda has been providing Information Technology (IT), business software, web and mobile development services to organizations of all.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alvarorobledo.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Alvaro Robledo
  links:
    - https://www.linkedin.com/in/alvaro-robledo
    - https://medium.com/@alvarorobledo
    - https://www.instagram.com/alvarorobledo_
    - https://github.com/alvarorobledo
    - https://www.kaggle.com/alvarobledo

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/blog'}
  - {name: 'About me', link: '/about-me'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Contact', link: '/contact'}

home_title: Hi! I'm Alvaro
tagline: >
  I'm a final year Electrical & Electronic Engineering with Management student at Imperial College London. I am interested in machine learning and start-ups.

blog_title: Blog
blog_tagline: >
  Welcome to my little corner of the Web. This blog is mainly just a jumble of my thoughts and interests, with a focus on data science.

home_hero_img: home/background.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
blog_hero_img: blog/background.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: alvarobledo@gmail.com # email for form submission

# twitter_username: tw_username # replace with your_twitter_username or comment to remove link from footer
github_username:  alvarorobledo # replace with your_github_username or comment to remove link from footer
instagram_username: alvarorobledo_ # replace with your_instagram_username or comment to remove link from footer
linkedin_username: alvaro-robledo
medium_username: alvarorobledo
kaggle_username: alvarobledo

disqus:
  shortname: hamsoft # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-NXJLPTG # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /blog/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
