title: Hamsoft Uganda
author: Hamsoft Uganda
description: > # Meta description of Homepage
  Since 2013, Hamsoft Uganda has been providing Information Technology (IT), business software, web and mobile development services to organizations,We develop and distribute computer software that can be used to learn, instruct, assess, calculate, entertain, or perform a multitude of tasks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.hamsoftug.com" # the base hostname & protocol for your site, e.g. http://example.com

logo: /assets/img/posts/mx.jpg

twitter:
  username: hamsoftuganda
  card: summary_large_image
  creator: @HamsoftUganda
  image: /assets/img/posts/mx.jpg
  description: We develop and distribute computer software that can be used to learn, instruct, assess, calculate, entertain, or perform a multitude of tasks.
  title: Blog Hamsoft Uganda
# SEO PLUGIN
social:
  name: Hamsoft Uganda
  links:
    - https://www.linkedin.com/in/hamsoftug
    - https://medium.com/@stevebaros
    - https://www.instagram.com/hamsoftug
    - https://github.com/hamsoftug
    - https://www.kaggle.com/hamsoftug




defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/posts/mx.jpg
      author: hamsoftuganda

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: 'https://hamsoftug.com'}
  - {name: 'Blog', link: '/'}
  - {name: 'Geo IP', link: '/geoip'}
  - {name: 'CashBook', link: '/cashflow'}

home_title: Hi! there ,Welcome aboard
tagline: >
  We develop and distribute computer software that can be used to learn, instruct, assess, calculate, entertain, or perform a multitude of tasks..

blog_title: Blog
blog_tagline: >
   This blog is mainly focused on the day to day discoveries at workplaces and forums.

home_hero_img: home/background.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
blog_hero_img: blog/background.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: info@hamsoftug.com # email for form submission

# twitter_username: tw_username # replace with your_twitter_username or comment to remove link from footer
github_username:  hamsoftug # replace with your_github_username or comment to remove link from footer
instagram_username: hamsoftug # replace with your_instagram_username or comment to remove link from footer
linkedin_username: hamsoftug
medium_username: stevebaros
kaggle_username: hamsoftug

disqus:
  shortname: hamsoft # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-PP5F2QL # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /blog/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
